export enum Permission {
    TICKET_CREATE = 'TICKET_CREATE',
    TICKET_VIEW = 'TICKET_VIEW',
    TICKET_ASSIGN = 'TICKET_ASSIGN',
    TICKET_UPDATE = 'TICKET_UPDATE',
    TICKET_DELETE = 'TICKET_DELETE'
  }
  